<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mint.Domain\Mint.Domain.csproj" />
    <ProjectReference Include="..\Mint.Entity\Mint.Entity.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Npgsql" Version="8.0.0" />
    <PackageReference Include="SqlSugarCore" Version="5.1.4.182" />
    <PackageReference Include="Autofac" Version="8.0.0" />
    <PackageReference Include="AutoMapper" Version="8.0.0" />
    <PackageReference Include="Confluent.Kafka" Version="1.8.2" />
    <PackageReference Include="CSRedisCore" Version="3.8.803" />
    <PackageReference Include="EPPlus.Core" Version="1.5.4" />
    <PackageReference Include="Microsoft.Extensions.Caching.Redis.Core" Version="1.0.3" />
    <PackageReference Include="Quartz" Version="3.4.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.35.0" />
    <PackageReference Include="ZKWeb.System.Drawing" Version="4.0.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.88.7" />
    <PackageReference Include="Arric.Crypto.SM" Version="1.1.2" />
    <PackageReference Include="Yitter.IdGenerator" Version="1.0.14" />
  </ItemGroup>

</Project>
